export const songs = [
  { path: "./@favourites/2 - acidil.js" },
  { path: "./@favourites/acidpoly.js" },
  { path: "./@favourites/basic-techno.js" },
  { path: "./@favourites/elevator-going-down.js" },
  { path: "./@favourites/elevator.js" },
  { path: "./@favourites/interstellar.js" },
  { path: "./@favourites/monster-bass.js" },
  { path: "./@favourites/strangerthings.js" },
  { path: "./@favourites/switchangel_acid.js" },
  { path: "./@favourites/trance_02.js" },
  { path: "./@favourites/whydoesmybrain.js" },
  { path: "./chrisZdk/Barok.js" },
  { path: "./chrisZdk/Havana.js" },
  { path: "./chrisZdk/Radical.js" },
  { path: "./chrisZdk/Serene.js" },
  { path: "./chrisZdk/acidpoly.js" },
  { path: "./chrisZdk/humilis.js" },
  { path: "./chrisZdk/nervous.js" },
  { path: "./classical alt/fur-elise-mutopia.js" },
  { path: "./classical alt/fur-elise.js" },
  { path: "./classical alt/liszt-la-campanella-01.js" },
  { path: "./classical/bach-fugue-bwv849.js" },
  { path: "./classical/beethoven-fur-elise.js" },
  { path: "./classical/beethoven-rondo-a-capriccio.js" },
  { path: "./classical/chopin-etude-op10no2.js" },
  { path: "./classical/chopin-etude-op10no5.js" },
  { path: "./classical/chopin-etude-op10no9.js" },
  { path: "./classical/liszt-la-campanella-1838.js" },
  { path: "./classical/liszt-la-campanella.js" },
  { path: "./classical/moonlight-sonata.js" },
  { path: "./classical/mozart-alla-turca.js" },
  { path: "./comp-phys-marc/electronic.js" },
  { path: "./comp-phys-marc/lofi_loop.js" },
  { path: "./comp-phys-marc/piano_loop.js" },
  { path: "./darkmarthur/13 - dubtechno.js" },
  { path: "./darkmarthur/2 - acidil.js" },
  { path: "./darkmarthur/8 - trance & bass.js" },
  { path: "./dotcomdudee/strangerthings_drumandbass.js" },
  { path: "./dotcomdudee/switchangel_acid.js" },
  { path: "./eefano/anniesroom.js" },
  { path: "./eefano/cadenza.js" },
  { path: "./eefano/clandeisiciliani.js" },
  { path: "./eefano/strangerthings.js" },
  { path: "./eefano/swimmingsnake.js" },
  { path: "./eefano/veronicainecstasy.js" },
  { path: "./eefano/veronicazigzag.js" },
  { path: "./eefano/waltzno2.js" },
  { path: "./eefano/whydoesmybrain.js" },
  { path: "./eefano/woodeneye.js" },
  { path: "./experiments/classical-claude-opus-4.6/alla-turca.js" },
  { path: "./experiments/classical-claude-opus-4.6/beethoven-sonata2-allegro-vivace.js" },
  { path: "./experiments/classical-claude-opus-4.6/beethoven-sonata2-largo.js" },
  { path: "./experiments/classical-claude-opus-4.6/beethoven-sonata2-rondo.js" },
  { path: "./experiments/classical-claude-opus-4.6/beethoven-sonata2-scherzo.js" },
  { path: "./experiments/classical-claude-opus-4.6/fur-elise.js" },
  { path: "./experiments/classical-claude-opus-4.6/liszt-ballade-no2.js" },
  { path: "./experiments/classical-claude-opus-4.6/moonlight-sonata.js" },
  { path: "./experiments/classical-gemini-3.3/alla-turca.js" },
  { path: "./experiments/classical-gemini-3.3/la-campanella.js" },
  { path: "./experiments/classical-gpt-5.4-mini/alla-turca.js" },
  { path: "./experiments/classical-gpt-5.4-mini/fur-elise.js" },
  { path: "./experiments/classical-gpt-5.4-mini/la-campanella.js" },
  { path: "./experiments/classical-gpt-5.4-mini/moonlight-sonata.js" },
  { path: "./fran0x/hysteria.js" },
  { path: "./fran0x/interstellar.js" },
  { path: "./fran0x/rock_pop.js" },
  { path: "./fran0x/stranger_things.js" },
  { path: "./fran0x/trance_01.js" },
  { path: "./fran0x/trance_02.js" },
  { path: "./honcoops/01_driving_bassline.js" },
  { path: "./honcoops/02_euphoric_leads.js" },
  { path: "./honcoops/03_buildups_breakdowns.js" },
  { path: "./honcoops/04_classic_chord_progression.js" },
  { path: "./honcoops/example_09_extended.js" },
  { path: "./honcoops/example_10_extended.js" },
  { path: "./smaudd/basic-techno.js" },
  { path: "./smaudd/bibimbum.js" },
  { path: "./smaudd/elevator-going-down.js" },
  { path: "./smaudd/elevator.js" },
  { path: "./smaudd/hyped-up.js" },
  { path: "./smaudd/lofi-1.js" },
  { path: "./smaudd/marronlike.js" },
  { path: "./smaudd/monster-bass.js" },
  { path: "./smaudd/raw-kick.js" },
  { path: "./smaudd/sad-bk.js" },
  { path: "./smaudd/strudel-session-1.js" },
  { path: "./smaudd/techno-template.js" },
  { path: "./smaudd/templates.js" },
  { path: "./smaudd/today-is-blue.js" },
  { path: "./smaudd/two-islands.js" },
  { path: "./sueszli/rumble.js" },
  { path: "./sueszli/simple.js" },
  { path: "./sueszli/techno.js" },
  { path: "./sueszli/trance.js" },
  { path: "./various/Piano Demo.js" },
  { path: "./various/Switch Angel's live trance music coding.js" },
  { path: "./various/acid-bass.js" },
  { path: "./various/dj-dave-array.js" },
  { path: "./various/elvens-on-mars.js" },
  { path: "./various/finance.js" },
  { path: "./various/lo-fi-beat.js" },
  { path: "./various/music-4-machines.js" },
  { path: "./various/new-order-blue-monday.js" },
  { path: "./various/simple-techno.js" },
  { path: "./various/smalltown-boy.js" },
  { path: "./various/tcb-salvage.js" },
  { path: "./various/techno-a.js" },
  { path: "./various/techno-b.js" },
  { path: "./various/techno-song.js" },
  { path: "./various/todepons-dash-on-the-train.js" },
  { path: "./various/xcx-360-cover.js" },
];
